Repository MicrosoftDocs/dynamics-365-customer-engagement, pull requests merged in 2019-02, with the labels that each got.

#329 Update remote-assist-hololens.md
  remote-assist-hololens.md
Labels: assigned-to-contributors, doc-bug

#735 Update dynamics-365-app-outlook-user-s-guide.md
  ce/outlook-app/dynamics-365-app-outlook-user-s-guide.md
Labels: assigned-to-contributors

#790 Update pass-dynamics-365-data-page-parameter-ribbon-actions.md
  ce/developer/customize-dev/pass-dynamics-365-data-page-parameter-ribbon-actions.md
Labels: assigned-to-contributors

#758 Update enable-disable-security-field.md
  ce/admin/enable-disable-security-field.md
Labels: assigned-to-author, doc-enhancement

#812 Update prepare-marketing-emails.md
  ce/marketing/prepare-marketing-emails.md
Labels: assigned-to-contributors

#815 Update role.md
  ce/developer/entities/role.md
Labels: assigned-to-contributors
