Repository MicrosoftDocs/dynamics-365-customer-engagement, pull requests merged in 2019-01, with the labels that each got.

#677 Updated Sample to remove casting
  ce/snippets/csharp/CRMV8/quickstartcs/cs/simplifiedconnection.cs
Labels: assigned-to-contributors

#163 Return Type should be an Array
  ce/developer/clientapi/reference/Xrm-Utility/lookupObjects.md
Labels: assigned-to-contributors

#445 Typo in Map entity fields in PowerApps
  ce/customize/map-entity-fields.md
Labels: assigned-to-contributors

#690 Make it clear that tenant moves are currently not available
  ce/admin/move-instance-tenant.md
Labels: assigned-to-contributors

#42 Removed encoded spaces
  ce/basics/export-excel-dynamic-worksheet.md
  ce/developer/webapi/retrieve-entity-using-web-api.md
Labels: assigned-to-contributors, doc-enhancement, in-progress

#661 Update monitor-manage-processes.md
  ce/customize/monitor-manage-processes.md
Labels: assigned-to-contributors

#153 Update business-process-flows-overview.md
  ce/customize/business-process-flows-overview.md
Labels: assigned-to-contributors

#665 Update manage-sharepoint-documents.md
  ce/portals/manage-sharepoint-documents.md
Labels: assigned-to-contributors, in-progress

#723 Update deploy-dynamics-365-app-for-outlook.md
  ce/outlook-app/deploy-dynamics-365-app-for-outlook.md
Labels: assigned-to-contributors

#290 Updated typos in additional parameters table
  ce/analytics/use-parameters-in-reports.md
Labels: assigned-to-contributors
