Repository MicrosoftDocs/dynamics-365-customer-engagement, pull requests merged in 2022-02, with the labels that each got.

#2508 Dana martens patch 1
  ce/customerengagement/on-premises/admin/connect-dynamics-365-on-premises-exchange-online.md
Labels: assigned-to-contributors

#2534 RELEASE NOTES UPDATES
  ce/field-service/version-history.md
Labels: assigned-to-contributors, Ready for CP

#2535 RELEASE NOTES
  ce/shared/urs/urs-bug-fixes.md
Labels: Ready for CP

#2549 Akhi branch
  ce/marketing/teams-how-to-follow-up.md
  ce/marketing/teams-webinar-follow-up.md
Labels: assigned-to-contributors

#2532 Mention option for auto-tracking sent items
  ce/outlook-addin/user-guide/set-option-automatically-track-incoming-outlook-email.md
Labels: assigned-to-contributors
