Repository MicrosoftDocs/dynamics-365-customer-engagement, pull requests merged in 2022-06, with the labels that each got.

#2636 Update real-time-marketing-custom-actions.md
  ce/marketing/media/Adding-custom-trigger-step1.png
  ce/marketing/media/add-another-custom-trigger-step5.png
  ce/marketing/media/chained-journey-via-custom-trigger.png
  ce/marketing/media/create-automated-flow-step8.png
  ce/marketing/media/create-automated-flow-step9.png
  ce/marketing/media/map-custom-trigger-attribute-step3.png
  ce/marketing/media/map-custom-trigger-attribute-step4.png
  ce/marketing/media/map-custom-trigger-attribute-step6.png
  ce/marketing/media/map-custom-trigger-attribute-step7.png
  ce/marketing/media/viewing-custom-trigger-usage-step2.png
  ce/marketing/real-time-marketing-custom-actions.md
Labels: assigned-to-contributors

#2641 Update download-tools-nuget.md
  ce/customerengagement/on-premises/developer/download-tools-nuget.md
Labels: assigned-to-contributors, do-not-merge

#2509 Improved Entity Ownership section
  ce/customerengagement/on-premises/developer/introduction-entities.md
Labels: assigned-to-contributors

#2499 Update use-access-teams-owner-teams-collaborate-share-information.md
  ce/customerengagement/on-premises/developer/use-access-teams-owner-teams-collaborate-share-information.md
Labels: waiting on internal feedback
