Repository MicrosoftDocs/dynamics-365-customer-engagement, pull requests merged in 2022-09, with the labels that each got.

#2708 Add note on usage of email links in Condition Tiles
  ce/marketing/customer-journey-tiles-reference.md
Labels: assigned-to-contributors

#2715 Update preview-schedule-board.md
  ce/field-service/media/schedule-board-new-sitemap-before.png
  ce/shared/urs/preview-schedule-board.md
Labels: assigned-to-contributors

#2711 Update insights.md
  ce/marketing/insights.md
Labels: assigned-to-contributors

#2724 Update migrate-files.md
  ce/marketing/developer/migrate-files.md
Labels: assigned-to-contributors

#2722 update customer-journey-tiles-reference.md
  ce/marketing/customer-journey-tiles-reference.md
Labels: assigned-to-contributors

#2721 Update documentation of setting expiration date on email tiles
  ce/marketing/email-expire.md
Labels: assigned-to-contributors

#2699 Update upload-images-files.md
  ce/marketing/upload-images-files.md
Labels: assigned-to-contributors, August 2022 release

#2698 Update real-time-marketing-asset-library.md
  ce/marketing/real-time-marketing-asset-library.md
Labels: assigned-to-contributors, August 2022 release

#2729 Update suppression-lists.md
  ce/marketing/suppression-lists.md
Labels: assigned-to-contributors

#2733 Update mkt-settings-default-marketing.md
  ce/marketing/mkt-settings-default-marketing.md
Labels: assigned-to-contributors

#2731 Update gdpr-use-features.md
  ce/marketing/gdpr-use-features.md
Labels: assigned-to-contributors

#2732 Update customer-journey-tiles-reference.md
  ce/marketing/customer-journey-tiles-reference.md
Labels: assigned-to-contributors

#2738 Update real-time-marketing-asset-add-on.md
  ce/marketing/real-time-marketing-asset-add-on.md
Labels: assigned-to-contributors

#2742 Update real-time-marketing-asset-add-on.md
  ce/marketing/real-time-marketing-asset-add-on.md
Labels: assigned-to-contributors

#2743 Update fair-use-policy.md
  ce/marketing/fair-use-policy.md
Labels: assigned-to-contributors

#2716 remove duplicate paragraph in `set-option-automatically-track-incomin…
  ce/outlook-addin/user-guide/set-option-automatically-track-incoming-outlook-email.md
Labels: assigned-to-contributors

#2749 Rendered as source code instead of text
  ce/outlook-addin/admin-guide/install.md
Labels: assigned-to-contributors

#2713 Change "Select Options" to "Select Personalization Settings"
  ce/customerengagement/on-premises/basics/set-personal-options.md
Labels: assigned-to-contributors

#2730 Correct TSI instructions
  ce/field-service/installation-setup-iothub.md
Labels: assigned-to-contributors, field-service-core, dynamics-365-field-service
